name: my-first-workflow
on: [push]

jobs:
   run-shell-commands: 
    runs-on:  windows-latest
    steps:
      - name: echo a string 
        run: |
           $BRANCH_NAME=$(echo '${{ github.ref }}')
           echo $BRANCH_NAME
      
